name: AnalyseDeDonneesWorkflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Récupération du dépôt
      uses: actions/checkout@v2

    - name: Configuration de Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Installation de pip
      run: |
        Invoke-WebRequest -Uri https://bootstrap.pypa.io/get-pip.py -OutFile get-pip.py
        python get-pip.py --force-reinstall
        python -m pip install --upgrade pip

    - name: Installation de Jupyter
      run: |
        python -m pip install jupyter

    - name: Installation des dépendances
      run: |
        python -m pip install opencv-python tensorflow numpy matplotlib imageio
       
        # Vous pourriez avoir besoin d'étapes de configuration supplémentaires pour votre environnement

    - name: Convertir le notebook Jupyter en script Python
      run: jupyter nbconvert --to script --output heartdis heartdis.ipynb

    - name: Exécuter le script Python
      run: python heartdis.py

